services:
  inventory:
    container_name: inventory
    build:
      context: ../code/inventory/src/Inventory.WebApi
      dockerfile: Dockerfile
    image: globaltickets.inventory:latest
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000

  customer:
    container_name: customer
    build:
      context: ../code/customer/src/Customer.WebApi
      dockerfile: Dockerfile
    image: globaltickets.customer:latest
    ports:
      - "7000:7000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000

  order:
    container_name: order
    build:
      context: ../code/ordering/src/Ordering.WebApi
      dockerfile: Dockerfile
    image: globaltickets.order:latest
    ports:
      - "6000:6000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000
