name: Build and Push Image For Inventory

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      imageRepository: "globaltickets.inventory"
      containerRegistry: "globalticketsacr.azurecr.io"
      dockerfilePath: "code/inventory/src/Inventory.WebApi/Dockerfile"
      deploymentFile: "inventory.yaml"
      namespace: "globaltickets"

    steps:
      - uses: actions/checkout@v4

      - name: Print Current Directory
        run: pwd

      - name: List All Files in Repository
        run: ls -R

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Re-Tag Previous Latest
        run: |
          set -e
          if docker pull ghcr.io/${{ github.repository }}/inventory:latest; then 
            echo "Successfully pulled :latest image, proceeding to re-tag."
            docker tag ghcr.io/${{ github.repository }}/inventory:latest ghcr.io/${{ github.repository }}/inventory:${{ github.run_number }}
            docker push ghcr.io/${{ github.repository }}/inventory:${{ github.run_number }}
          else
            echo "No existing :latest image to re-tag"
          fi

      - name: Build an image from Dockerfile
        run: |
          docker build -t ghcr.io/${{ github.repository }}/inventory:latest -f ${{ env.dockerfilePath }} ${{ github.workspace }}

      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/inventory:latest
