name: Build and Push Image For Inventory

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      imageRepository: "globaltickets.inventory"
      containerRegistry: "globalticketsacr.azurecr.io"
      dockerfilePath: "code/inventory/src/Inventory.WebApi/Dockerfile"
      deploymentFile: "inventory.yaml"
      namespace: "globaltickets"

    steps:
      - uses: actions/checkout@v4

      - name: Print Current Directory
        run: pwd

      - name: List All Files in Repository
        run: ls -R

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.containerRegistry }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: Re-Tag Previous Latest (Optional)
        run: |
          docker pull ${{env.containerRegistry}}/${{env.imageRepository}}:latest || echo "No existing :latest image to re-tag"
          docker tag ${{env.containerRegistry}}/${{env.imageRepository}}:latest ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}
          docker push ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}

      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}} -f ${{env.dockerfilePath}} ${{github.workspace}}

      - name: push image to ACR
        run: |
          docker push ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}

      - name: Echo Build.BuildId
        run: echo Build.BuildId=${{github.run_number}}

      - name: Echo github.run_number
        run: echo github.run_number=${{github.run_number}}

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: ${{github.workspace}}/k8s/remote/${{env.deploymentFile}}
        env:
          Build.BuildId: ${{github.run_number}}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployfile
          path: ${{github.workspace}}/k8s/remote/${{env.deploymentFile}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: deployfile

      # ...removed Azure deployment steps...
