name: Create Kubernetes Namespace

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-namespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Print Current Directory
        run: pwd

      - name: List All Files in Repository
        run: ls -R

      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}}
        id: setcontext

      - name: Apply namespace
        run: kubectl apply -${{github.workspace}}/k8s/remote/namespace.yaml
