name: Create Kubernetes Namespace

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-namespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for sparse checkout
          sparse-checkout: |
            k8s

      - name: Print Current Directory
        run: pwd

      - name: List All Files in Repository
        run: ls -R

      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}}
        id: setcontext

      - uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./remote/namespace.yaml
            ./dashboard/service-account.yaml
            ./dashboard/cluster-role-binding.yml

      - name: Deploy Kubernetes Dashboard
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
